/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001c3b',
        'tertiary-fixed-dim': '#ffb3af',
        'surface-dim': '#cadbf6',
        outline: '#74777f',
        'success-badge': '#1B998B',
        'border-subtle': '#DCE3EB',
        surface: '#f8f9ff',
        'on-primary': '#ffffff',
        'surface-tint': '#495f82',
        'on-tertiary-fixed-variant': '#930018',
        'on-tertiary-container': '#ff454c',
        'on-tertiary-fixed': '#410005',
        secondary: '#385ca6',
        tertiary: '#2a0002',
        'surface-page': '#F8F9FA',
        'on-secondary-fixed-variant': '#1b448d',
        'on-surface-variant': '#44474e',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#b0c6ff',
        'surface-container': '#e5eeff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#164089',
        'tertiary-container': '#520008',
        'navy-deep': '#03204C',
        'surface-subtle': '#EDF2F7',
        'surface-container-low': '#eff4ff',
        'inverse-surface': '#203146',
        'on-surface': '#0a1c30',
        'inverse-primary': '#b1c7f0',
        'inverse-on-surface': '#eaf1ff',
        'secondary-container': '#8eafff',
        background: '#f8f9ff',
        'on-error-container': '#93000a',
        'outline-variant': '#c4c6cf',
        'primary-fixed-dim': '#b1c7f0',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#314769',
        'error-container': '#ffdad6',
        'primary-fixed': '#d5e3ff',
        'surface-bright': '#f8f9ff',
        error: '#ba1a1a',
        'accent-red-hover': '#EF233C',
        'on-secondary-fixed': '#001944',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dce9ff',
        'surface-card': '#FFFFFF',
        'surface-variant': '#d2e4ff',
        primary: '#0B2545',
        'primary-container': '#0b2545',
        'surface-container-highest': '#d2e4ff',
        'on-background': '#0a1c30',
        'tertiary-fixed': '#ffdad7',
        'on-primary-container': '#778db2',
        'secondary-fixed': '#d9e2ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        margin: '2rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        gutter: '1.5rem',
        'space-2xl': '4rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        heading: ['Manrope', 'sans-serif'],
        body: ['"Source Sans 3"', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl-mobile': ['34px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'metric-display': ['44px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '700' }],
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
  plugins: [],
}
